/**
 * KernelManager — singleton facade over the session module.
 *
 * Thin wrapper that re-exports the session operations, constructing any
 * intermediate config structs so callers only need to supply a name and
 * optional kernel path.
 */

import type { SessionConfig, SessionInfo, SessionSnapshot, ExecutionResult } from './types.js';
import {
  createSession,
  deleteSession,
  executeInSession,
  listSessions,
  getSessionVariables,
  saveSessionSnapshot,
} from './session.js';

export class KernelManager {
  private static instance: KernelManager;

  /** Return the singleton instance, creating it on first access. */
  static getInstance(): KernelManager {
    if (!KernelManager.instance) {
      KernelManager.instance = new KernelManager();
    }
    return KernelManager.instance;
  }

  /**
   * Create a new Wolfram kernel session.
   *
   * @param name   A human-readable label for the session.
   * @param kernelPath  Optional path to MathKernel binary (defaults to wolframscript).
   */
  async createSession(name: string, kernelPath?: string): Promise<SessionInfo> {
    const config: SessionConfig = {
      id: '', // generated by the session module
      name,
      createdAt: new Date(),
      kernelPath,
    };
    return createSession(config);
  }

  /** Execute Wolfram Language code in the named session. */
  async execute(sessionId: string, code: string): Promise<ExecutionResult> {
    return executeInSession(sessionId, code);
  }

  /** Tear down a session, killing its kernel process. */
  async delete(sessionId: string): Promise<void> {
    await deleteSession(sessionId);
  }

  /** List all active sessions. */
  list(): SessionInfo[] {
    return listSessions();
  }

  /** Retrieve the current list of global variable names for a session. */
  async getVariables(sessionId: string): Promise<string[]> {
    return getSessionVariables(sessionId);
  }

  /** Save a snapshot of the current definitions in a session. */
  async snapshot(sessionId: string): Promise<SessionSnapshot> {
    return saveSessionSnapshot(sessionId);
  }
}
